#!/bin/bash

if [[ -z ${DESKPRO_KEY} ]]; then
  echo Please set the environment variable DESKPRO_KEY
  exit 1
fi

sm2 -start MONGO DATASTREAM 

sm2 -start THIRD_PARTY_DEVELOPER_FRONTEND THIRD_PARTY_APPLICATION THIRD_PARTY_DELEGATED_AUTHORITY THIRD_PARTY_ORCHESTRATOR

sm2 -start THIRD_PARTY_DEVELOPER API_PLATFORM_MICROSERVICE API_DEFINITION INTERNAL_AUTH UPSCAN_STUB

sm2 -start API_PLATFORM_DESKPRO --appendArgs '{"API_PLATFORM_DESKPRO":["-Ddeskpro.api-key='${DESKPRO_KEY}'"]}'

./run_local.sh
